"""atualiza_modelo_material

Revision ID: 5b50aa7a80cd
Revises: c10a20260912
Create Date: 2026-09-19 10:31:48.833598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b50aa7a80cd'
down_revision: Union[str, Sequence[str], None] = 'c10a20260912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materiais', sa.Column('disciplina_id', sa.Integer(), nullable=False))
    op.add_column('materiais', sa.Column('content_type', sa.String(length=100), nullable=False))
    op.add_column('materiais', sa.Column('tamanho_bytes', sa.Integer(), nullable=False))
    op.drop_constraint('materiais_id_grupo_fkey', 'materiais', type_='foreignkey')
    op.create_foreign_key(None, 'materiais', 'disciplinas', ['disciplina_id'], ['id'], ondelete='CASCADE')
    op.drop_column('materiais', 'id_grupo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materiais', sa.Column('id_grupo', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'materiais', type_='foreignkey')
    op.create_foreign_key('materiais_id_grupo_fkey', 'materiais', 'grupos', ['id_grupo'], ['id_grupo'])
    op.drop_column('materiais', 'tamanho_bytes')
    op.drop_column('materiais', 'content_type')
    op.drop_column('materiais', 'disciplina_id')
    # ### end Alembic commands ###
