"""substitui feito por status em tarefas

Revision ID: 9e3495daef5e
Revises: 08541a3b1747
Create Date: 2026-09-11 13:24:12.594374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e3495daef5e'
down_revision: Union[str, Sequence[str], None] = '08541a3b1747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('tarefas', sa.Column('status', sa.String(), nullable=True))
    op.execute("UPDATE tarefas SET status = 'a_fazer' WHERE feito = FALSE")
    op.execute("UPDATE tarefas SET status = 'concluido' WHERE feito = TRUE")
    op.alter_column('tarefas', 'status', nullable=False)
    op.drop_column('tarefas', 'feito')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarefas', sa.Column('feito', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('tarefas', 'status')
    # ### end Alembic commands ###
