"""cria tabelas da modelagem

Revision ID: b10a20260912
Revises: 9ad6d7063717
Create Date: 2026-09-12 19:36:23.598795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b10a20260912'
down_revision: Union[str, Sequence[str], None] = '9ad6d7063717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplinas',
    sa.Column('id_disciplina', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_disciplina')
    )
    op.create_index(op.f('ix_disciplinas_id_disciplina'), 'disciplinas', ['id_disciplina'], unique=False)
    op.create_table('grupos',
    sa.Column('id_grupo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_grupo')
    )
    op.create_index(op.f('ix_grupos_id_grupo'), 'grupos', ['id_grupo'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_index(op.f('ix_usuarios_login'), 'usuarios', ['login'], unique=True)
    op.create_table('colunas_kanban',
    sa.Column('id_coluna', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_grupo'], ['grupos.id_grupo'], ),
    sa.PrimaryKeyConstraint('id_coluna')
    )
    op.create_index(op.f('ix_colunas_kanban_id_coluna'), 'colunas_kanban', ['id_coluna'], unique=False)
    op.create_table('grupos_disciplinas',
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('id_disciplina', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_disciplina'], ['disciplinas.id_disciplina'], ),
    sa.ForeignKeyConstraint(['id_grupo'], ['grupos.id_grupo'], ),
    sa.PrimaryKeyConstraint('id_grupo', 'id_disciplina')
    )
    op.create_table('materiais',
    sa.Column('id_material', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('url_arquivo', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('data_upload', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_grupo'], ['grupos.id_grupo'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_material')
    )
    op.create_index(op.f('ix_materiais_id_material'), 'materiais', ['id_material'], unique=False)
    op.create_table('membros_grupo',
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_grupo'], ['grupos.id_grupo'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_grupo', 'id_usuario')
    )
    op.create_table('resumos',
    sa.Column('id_resumo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_disciplina', sa.Integer(), nullable=False),
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_disciplina'], ['disciplinas.id_disciplina'], ),
    sa.ForeignKeyConstraint(['id_grupo'], ['grupos.id_grupo'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_resumo')
    )
    op.create_index(op.f('ix_resumos_id_resumo'), 'resumos', ['id_resumo'], unique=False)
    op.create_table('subgrupos',
    sa.Column('id_grupo_pai', sa.Integer(), nullable=False),
    sa.Column('id_grupo_filho', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_grupo_filho'], ['grupos.id_grupo'], ),
    sa.ForeignKeyConstraint(['id_grupo_pai'], ['grupos.id_grupo'], ),
    sa.PrimaryKeyConstraint('id_grupo_pai', 'id_grupo_filho')
    )
    op.create_table('compartilhamentos',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['materiais.id_material'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_material')
    )
    op.create_table('materiais_grupos',
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_grupo'], ['grupos.id_grupo'], ),
    sa.ForeignKeyConstraint(['id_material'], ['materiais.id_material'], ),
    sa.PrimaryKeyConstraint('id_material', 'id_grupo')
    )
    op.create_table('tarefas',
    sa.Column('id_tarefa', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_coluna', sa.Integer(), nullable=False),
    sa.Column('id_disciplina', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_prazo', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_coluna'], ['colunas_kanban.id_coluna'], ),
    sa.ForeignKeyConstraint(['id_disciplina'], ['disciplinas.id_disciplina'], ),
    sa.PrimaryKeyConstraint('id_tarefa')
    )
    op.create_index(op.f('ix_tarefas_id_tarefa'), 'tarefas', ['id_tarefa'], unique=False)
    op.create_table('tarefas_responsaveis',
    sa.Column('id_tarefa', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tarefa'], ['tarefas.id_tarefa'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_tarefa', 'id_usuario')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarefas_responsaveis')
    op.drop_index(op.f('ix_tarefas_id_tarefa'), table_name='tarefas')
    op.drop_table('tarefas')
    op.drop_table('materiais_grupos')
    op.drop_table('compartilhamentos')
    op.drop_table('subgrupos')
    op.drop_index(op.f('ix_resumos_id_resumo'), table_name='resumos')
    op.drop_table('resumos')
    op.drop_table('membros_grupo')
    op.drop_index(op.f('ix_materiais_id_material'), table_name='materiais')
    op.drop_table('materiais')
    op.drop_table('grupos_disciplinas')
    op.drop_index(op.f('ix_colunas_kanban_id_coluna'), table_name='colunas_kanban')
    op.drop_table('colunas_kanban')
    op.drop_index(op.f('ix_usuarios_login'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_grupos_id_grupo'), table_name='grupos')
    op.drop_table('grupos')
    op.drop_index(op.f('ix_disciplinas_id_disciplina'), table_name='disciplinas')
    op.drop_table('disciplinas')
    # ### end Alembic commands ###
