"""adiciona sessoes de autenticacao

Revision ID: b20a20260912
Revises: b10a20260912
Create Date: 2026-09-12 19:37:05.052405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b20a20260912'
down_revision: Union[str, Sequence[str], None] = 'b10a20260912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessoes_auth',
    sa.Column('id_sessao', sa.String(length=36), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revogado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_sessao')
    )
    op.create_index(op.f('ix_sessoes_auth_expira_em'), 'sessoes_auth', ['expira_em'], unique=False)
    op.create_index(op.f('ix_sessoes_auth_id_usuario'), 'sessoes_auth', ['id_usuario'], unique=False)
    op.alter_column('usuarios', 'login',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'login',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_sessoes_auth_id_usuario'), table_name='sessoes_auth')
    op.drop_index(op.f('ix_sessoes_auth_expira_em'), table_name='sessoes_auth')
    op.drop_table('sessoes_auth')
    # ### end Alembic commands ###
