"""adiciona perfil do usuario

Revision ID: c10a20260912
Revises: b20a20260912
Create Date: 2026-09-12 19:56:14.284756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c10a20260912'
down_revision: Union[str, Sequence[str], None] = 'b20a20260912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfis_usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome_inicial', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.String(length=300), nullable=False),
    sa.Column('interesses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('notificar_tarefas', sa.Boolean(), nullable=False),
    sa.Column('notificar_grupos', sa.Boolean(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perfis_usuarios')
    # ### end Alembic commands ###
